# Generated by Django 4.2 on 2024-01-09 02:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("detectmodel", "0002_dangermodel_delete_uploadedimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dangermodel",
            name="user",
        ),
    ]
