# Generated by Django 4.2 on 2024-01-09 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("detectmodel", "0003_remove_dangermodel_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="dangermodel",
            name="user",
            field=models.ForeignKey(
                default=11,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
