# Generated by Django 4.2 on 2023-12-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_person_name_user_phone_number_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.CharField(max_length=15, null=True, verbose_name="회사"),
        ),
        migrations.AlterField(
            model_name="user",
            name="person_name",
            field=models.CharField(max_length=20, null=True, verbose_name="이름"),
        ),
    ]
